version: '3'

services:

  ### Workspace Utilities ##################################
  workspace:
    image: docker-registry.example.lara/laradock_workspace:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      labels:
      - traefik.frontend.rule=Host:abc.swarm.example.lara
      - traefik.frontend.whitelist.sourceRange=127.0.0.1,192.168.1.143,192.30.252.0/22,185.199.108.0/22,140.82.112.0/20
      - traefik.docker.network=traefik
    volumes:
    - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    extra_hosts:
    - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    environment:
    - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}

  ### PHP-FPM ##############################################
  php-fpm:
    image: docker-registry.example.lara/laradock_php-fpm:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      labels:
      - traefik.frontend.whitelist.sourceRange=127.0.0.1,192.168.1.143,192.30.252.0/22,185.199.108.0/22,140.82.112.0/20
      - traefik.docker.network=traefik
    volumes:
    - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    extra_hosts:
    - "dockerhost:${DOCKER_HOST_IP}"
    environment:
    - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    - FAKETIME=${PHP_FPM_FAKETIME}
    depends_on:
    - workspace

  ### MySQL ################################################
  mysql:
    image: docker-registry.example.lara/laradock_mysql:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      labels:
      - traefik.frontend.whitelist.sourceRange=127.0.0.1,192.168.1.143,192.30.252.0/22,185.199.108.0/22,140.82.112.0/20
      - traefik.docker.network=traefik
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - TZ=${WORKSPACE_TIMEZONE}
    volumes:
    - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
    - "${MYSQL_PORT}:3306"
