version: '3'

services:

  ### Workspace Utilities ##################################
  workspace:
    image: docker-registry.example.lara/laradock_workspace:latest
    extra_hosts:
    - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    environment:
    - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}

  ### PHP-FPM ##############################################
  php-fpm:
    image: docker-registry.example.lara/laradock_php-fpm:latest
    extra_hosts:
    - "dockerhost:${DOCKER_HOST_IP}"
    environment:
    - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    - FAKETIME=${PHP_FPM_FAKETIME}
    depends_on:
    - workspace

  ### MySQL ################################################
  mysql:
    image: docker-registry.example.lara/laradock_mysql:latest
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - TZ=${WORKSPACE_TIMEZONE}
    ports:
    - "${MYSQL_PORT}:3306"
